www.facebook.com/sona.biswas.330467 environment:
  secure_file_version: 1.0.1

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

skip_tags: true

init:
- set appveyor_full_version=%secure_file_version%.%appveyor_build_number%
- appveyor UpdateBuild -Version %appveyor_full_version%

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

build_script:
- build.cmd
- 7z a secure-file.zip %APPVEYOR_BUILD_FOLDER%\build\*
- appveyor PushArtifact secure-file.zip

test: off

deploy:
- provider: GitHub
  tag: $(secure_file_version)
  release: Secure File $(secure_file_version)
  auth_token:
    secure: avf7rJ4eX9x4b5bE/CX/nL6rQgUnNhSGTxxqMt+KyPU3yeOhHIE8q8NtmO10YOae
  force_update: true
